### ISSUE TITLE
Tasks route resource seems to go against the official documentation.

### ISSUE THREAD

**Issue by thinsoldier** [jeremykenedy/laravel-tasks#2]
```php
// USER TASKS ROUTES
Route::resource('/tasks', 'TasksController');
Route::resource('/tasks-all', 'TasksController@index_all');
Route::resource('/tasks-complete', 'TasksController@index_complete');
Route::resource('/tasks-incomplete', 'TasksController@index_incomplete');
```

From both the 5.2 and 5.4 documentation:

> Supplementing Resource Controllers
> If it becomes necessary to add additional routes to a resource controller beyond the default resource routes, you should define those routes before your call to Route::resource; otherwise, the routes defined by the resource method may unintentionally take precedence over your supplemental routes.
> https://laravel.com/docs/5.4/controllers#restful-supplementing-resource-controllers

I'm trying to update your project to Laravel 5.4 and asked a number of people to look at the original Task routes and they all said they can't believe these routes ever actually worked.

They don't work in 5.4 and to get them to work I had to follow the advice of the docs and move the 1 actual resource route to be last and make all the others plain _get_ routes.

```php
// USER TASKS ROUTES
Route::get('/tasks-all', 'TasksController@index_all');
Route::get('/tasks-incomplete', 'TasksController@index_incomplete');
Route::get('/tasks-complete', 'TasksController@index_complete');
Route::resource('/tasks', 'TasksController');
```

**Comment by jeremykenedy** [comment]
Correct it and do a pull request please.
